app/src/main/java/com/example/driveandroid/DaoActivity.kt

DaoActivityの不要import削除

---

.idea/.name
app/build.gradle
app/src/androidTest/java/com/example/driveandroid/ExampleInstrumentedTest.kt
app/src/main/java/com/example/driveandroid/CameraActivity.kt
app/src/main/java/com/example/driveandroid/FinishActivity.kt
app/src/main/java/com/example/driveandroid/Support.kt
app/src/test/java/com/example/driveandroid/ExampleUnitTest.kt
settings.gradle

パッケージ名driveandroidに修正

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderListAdapter.kt
app/src/main/res/layout/activity_folder_detail.xml

FolderListAdapter：folderidはposition＋1だったのでDetailへposition送る処理変更
FolderDetail：FolderInfoのデータを表示、日付はスラッシュを入れて表示　
detail.xml：id変更　
FolderCreate:日付の0埋め

データベースはそのまま、FolderDetailにFolderInfoの情報を表示する

---

app/src/main/java/com/example/driveandroid/DriveDBHelper.kt
app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderInfo.kt
app/src/main/java/com/example/driveandroid/FolderListActivity.kt
app/src/main/java/com/example/driveandroid/FolderListAdapter.kt

関係ファイルの日付（date）使用箇所をすべてString仕様に変更

FolderInfoテーブルのdateをTEXT(15)、Createでの登録はスラッシュ入りyyyy/MM/ddの形にする

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailAdapter.kt
app/src/main/java/com/example/driveandroid/FolderListAdapter.kt
app/src/main/java/com/example/driveandroid/ItemToUse.kt
app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt
app/src/main/res/layout/activity_folder_detail.xml
app/src/main/res/layout/item_to_use.xml

Paragraphinfoの登録処理完了、
RecyclerViewの中身は一人当たりの金額以外は表示できるようになりました。

Paragraphinfo登録と表示OK、一人当たりの金額のみ未完成

---

app/src/main/java/com/example/driveandroid/Constants.kt
app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderListActivity.kt
app/src/main/java/com/example/driveandroid/FolderListAdapter.kt
app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt

各ファイル変更概要
FolderList&FolderListAdapater：DELETE処理、folderId送りをpositionを使ったものに変更
FolderCreate：moneyInsertに送るfolderIdの変数初期化位置を変更
FolderDetail：前回変更コメントを削除したのみ

FolderListでのDELETE処理とfolderId送り修正、MoneyInsertでのSpinner表示修正

---

app/src/main/java/com/example/driveandroid/Constants.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailAdapter.kt
app/src/main/res/layout/item_to_use.xml

FolderDetailの項目削除処理OK

---

app/src/main/java/com/example/driveandroid/FolderListActivity.kt
app/src/main/res/layout/activity_folder_list.xml
app/src/main/res/values/strings.xml

FolderList：何も登録がない/なくなった場合のメッセージ表示
xml：メッセージのレイアウト追加
string：メッセージ内容追加

FolderListで何も登録がない場合のメッセージ表示

---

app/src/main/res/layout/activity_folder_create.xml
app/src/main/res/layout/activity_money_insert.xml
app/src/main/res/values/moneyinsert_spinner.xml
app/src/main/res/values/strings.xml

フォルダ作成画面と金額入力画面のプレースホルダー追加と、
フォルダ作成画面のスクロールビューを追加しました。

プレースホルダーとスクロールビュー追加

---

app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailAdapter.kt
app/src/main/res/layout/activity_folder_detail.xml
app/src/main/res/layout/item_to_use.xml
app/src/main/res/values/strings.xml

FolderDetail：項目金額を受け取り合計と合計の一人当たり金額を表示
FolderDetailAdapter：リスナーを使って項目金額をDetailに受け渡し、一人当たり金額表示
xml：iOSと同様にするためボタン位置調整
string：iOSと同様にするためボタンテキスト修正

FolderDetailでの金額表示

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt

金額入力の空白チェック

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/res/layout/activity_folder_create.xml

FolderCreate:文字数チェック、人数カウント処理追加
xml：inputLayoutを追加

FolderCreateでの文字数チェック、人数カウント処理追加

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt

完了系ボタン押下後の空白チェック、エラーダイアログ表示追加

---

app/build.gradle
app/src/debug/res/values/google_maps_api.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/MapsActivity.kt

現在地取得、使用許可ダイアログの表示、起動時に東京駅が表示されるようにしました。

MapsActivity現在地取得＆使用許可ダイアログ

---

app/src/main/res/layout/activity_folder_create.xml
app/src/main/res/layout/activity_folder_list.xml

List：登録なしのメッセージ位置調整
Create：日付・タイトル・メンバー名　の項目名文字サイズ調整

List、Createの文字表示　場所とサイズ調整

---

app/src/debug/res/values/google_maps_api.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/driveandroid/MapsActivity.kt

起動時には東京駅が表示され、現在地表示ボタンを押すと現在地にとべるように修正しました。

現在地表示のボタン追加、Manifestファイル訂正

---

app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt

カメラの権限ダイアログ調整、許可しなかった場合もアプリ操作できるように

---

app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt
app/src/main/res/layout/activity_money_insert.xml

MoneyInsertで背景タップをするとフォーカスが背景にうつるようにする

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/res/layout/activity_folder_create.xml

完了系ボタンの中で10文字チェック再度行うようにしてiOSと仕様を合わせる
背景をタップしても10文字チェックが走るようにする

FolderCreateでの完了系ボタンの処理に10文字チェック追加、背景タップでフォーカスが外れるようにする

---

app/build.gradle
app/src/main/java/com/example/driveandroid/MapsActivity.kt

位置の使用許可されている場合を現在地、拒否された場合を東京駅が表示されるように修正しました。

位置使用の許可/拒否の地図表示修正

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderListActivity.kt
app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt

波線ついているdialog,whichを「 _ 」に置き換え

ダイアログのはい/いいえのボタン配置、処理を入れ替え　

---

app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt
app/src/main/res/values/moneyinsert_spinner.xml

Detailから来た場合は「詳細に戻る」
Createから来た場合は「ホームに戻る」タイトル

項目の選択肢に飲食代を追加、MoneyInsertでの登録せず戻るダイアログでメッセージを分岐

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderListActivity.kt
app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

各ktファイルに設定したダイアログテーマを反映、黒に統一

---

app/src/main/res/layout/activity_folder_list.xml

フォルダ一覧の背景を更新

---

app/build.gradle
build.gradle

DeployGate接続のためbuild.gradleを更新

---

app/src/main/AndroidManifest.xml

アプリを縦画面固定にして欲しいと新井さんからお願いがありましたので、修正しました。

アプリを縦画面固定にする処理

---

app/src/main/java/com/example/driveandroid/FolderDetailAdapter.kt
app/src/main/res/layout/activity_folder_detail.xml
app/src/main/res/layout/item_to_use.xml
app/src/main/res/values/strings.xml

Adapterのデザイン修正を行いました。
また、その他細かな点も修正しました。

FolderDetailAdapter修正

---

app/src/main/java/com/example/driveandroid/PolicyActivity.kt
app/src/main/res/values/strings.xml

iOSと合わせるため、URLのクリック時にダイアログを表示するように修正しました。

利用規約のURLクリック時のダイアログ表示

---

app/src/main/res/layout/activity_folder_list.xml
app/src/main/res/values/strings.xml

メッセージの内容変更と、真ん中に表示されるように変更しました。

FolderListのデータ登録なしの場合のデザイン変更（iOSと同様にする）

---

app/src/main/res/layout/activity_money_insert.xml

端末によっては文字が大きすぎるため、サイズを小さくしました。

MoneyInsert文字微調整

---

app/src/main/res/layout/activity_folder_create.xml
app/src/main/res/layout/activity_money_insert.xml

フォルダ作成画面と金額入力画面の該当箇所に追加
古いコメント削除

入力部分にカーソルがあるときカーソルを表示する

---

app/build.gradle

SDKバージョンの最小を変更

---

app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailAdapter.kt

本日の報告会で、3桁区切りで金額表示させた方が見やすいとの意見をいただいたので、修正しました。

FolerDetailの金額部分を3桁区切りで表示させる

---

app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt

共有画面においても、金額がカンマ区切りで表示されるよう修正しました。

共有画面の金額表示をカンマ区切りにする

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/res/layout/activity_folder_create.xml

端末によっては日付選択をクリックした際に
エラーが出て表示されない問題が発生してしまったので
対応させるため、条件分岐し修正しました。

FolderCreateの日付欄修正

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/activity_folder_create.xml

メンバーやタイトルを入力する際にレイアウトが崩れていた問題の修正と
日付表示欄の文字サイズを修正しました。

入力時のレイアウト崩れを修正、日付表示欄の文字調整

---

app/src/main/AndroidManifest.xml
app/src/main/res/drawable/border.xml
app/src/main/res/layout/activity_money_insert.xml

・見やすいように背景に枠線を追加、
・カメラ起動後、縦画面固定ではなくなってしまう問題点を修正
以上の２点を修正しました。

背景の枠線追加、カメラ起動後縦画面固定

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/driveandroid/SupportActivity.kt
app/src/main/java/com/example/driveandroid/VersionActivity.kt
app/src/main/res/layout/activity_version.xml
app/src/main/res/values/strings.xml

アプリのバージョンがわかるように、バージョン情報の項目を追加しました。

バージョン情報の追加

---

app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/res/drawable/border.xml
app/src/main/res/layout/activity_folder_detail.xml

・金額入力画面から詳細画面に遷移する際に、使用項目の表示されない問題が発生していたので、
　項目の登録なしの場合でも使用項目が表示されるように変更しバグを修正しました。
・RecyclerViewの中身もスクロールされてしまう問題を修正しました。
・MoneyInsert同様、背景に枠線を追加しました。
・共有において、改行の追加と未登録の場合の文字表示を追加しました。

使用項目の表示されない問題とバグ修正、共有の文字表示、背景の枠線追加

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/res/layout/activity_folder_create.xml

・人数表示の位置、大きさの調整
・エラーの際にフォーカスが次の項目に移ってしまう問題を修正
・メンバー６（最後）の項目でenterを押してもエラーダイアログが表示されない問題を修正

人数表示の文字の大きさ変更、フォーカス関連の修正

---

app/src/main/java/com/example/driveandroid/Constants.kt
app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderListAdapter.kt
app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt
app/src/main/res/layout/activity_money_insert.xml
app/src/main/res/values/strings.xml

100万円以上の場合、エラーダイアログが表示されるように修正しました。
ダイアログのメッセージも修正しました。
また、全体の合計金額も100万円以上の場合エラー表示することになりましたが、そちらは現在修正中です。

ダイアログメッセージ修正、100万円以上の場合エラー表示

---

app/src/main/res/layout/activity_maps.xml

ツールバーのタイトルを「ドラログ」から「地図」に変更しました。

ツールバーの文字表示変更

---

app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt

サポート画面と共有画面から戻る時の処理でクリアタスクをしていなかったので
追加しました。

クリアタスク処理の追加

---

app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt

タスクボタン、ホームボタンが呼ばれてから戻る時に、
金額が倍に表示される問題があったので追加しました。

タスクボタン、ホームボタンが呼ばれた時の処理

---

app/src/main/res/values/strings.xml

iOSと合わせるため「はい」「いいえ」から「OK」「キャンセル」に変更しました。

×のダイアログメッセージ修正

---

app/build.gradle
app/src/debug/res/values/google_maps_api.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/driveandroid/FolderListActivity.kt
app/src/main/java/com/example/driveandroid/MapsActivity.kt
app/src/main/res/layout/activity_folder_list.xml

map機能をクローズ

---

app/src/main/java/com/example/driveandroid/FolderCreateActivity.kt
app/src/main/java/com/example/driveandroid/FolderDetailActivity.kt
app/src/main/java/com/example/driveandroid/FolderListActivity.kt
app/src/main/java/com/example/driveandroid/MoneyInsertActivity.kt
app/src/main/java/com/example/driveandroid/PolicyActivity.kt
app/src/main/java/com/example/driveandroid/SupportActivity.kt

ダイアログを　キャンセル／OK の並びに修正
